# image will be published to ghcr.io/<user>/<name>
name: gnome-main
# description will be included in the image's metadata
description: "CentOS Stream Atomic with GNOME Desktop"

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/centos-bootc/centos-bootc-dev
image-version: stream9 #experiment with version numbers, latest?

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/initialization-scripts.yml
  - from-file: common/gnome-packages.yml
  - from-file: common/gui-packages.yml
  - from-file: common/common-packages.yml
  - from-file: common/gui-scripts.yml
  - from-file: common/common-files.yml
  - from-file: common/common-scripts.yml
  - type: signing
  - type: yafti
